services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    ports:
      - 1989:1989
    environment:
      - COMPETITION_PATH=/app/competition
    volumes:
      - ./sample:/app/competition