FROM oven/bun:1-alpine AS build

# Set the working directory
WORKDIR /app
# Copy the necessary files
COPY . .
# Install dependencies
RUN bun install --frozen-lockfile --filter @progsoc/fj-svelte

ARG VITE_BACKEND_URL
# Set the environment variable for the backend URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
# Build the application
RUN bun run --filter @progsoc/fj-svelte build


FROM nginx
# Copy the built application from the previous stage
COPY --from=0 /app/clients/fj-svelte/dist /usr/share/nginx/html
# Copy the nginx configuration file
COPY clients/fj-svelte/nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port the app runs on
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]