mutation JudgeSubmission($problemSlug: ID!, $code: String!, $output: String!) {
	judge(slug: $problemSlug, code: $code, output: $output) {
		__typename

		... on JudgeSuccessOutput {
			message
		}

		... on JudgeErrorOutput {
			message
			errors
		}
	}
}
