/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProblemsImport } from './routes/problems'
import { Route as LeaderboardImport } from './routes/leaderboard'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as ProblemsIndexImport } from './routes/problems/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ProblemsSlugImport } from './routes/problems/$slug'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminClockImport } from './routes/admin/clock'

// Create/Update Routes

const ProblemsRoute = ProblemsImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProblemsIndexRoute = ProblemsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const ProblemsSlugRoute = ProblemsSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProblemsRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

const AdminClockRoute = AdminClockImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsImport
      parentRoute: typeof rootRoute
    }
    '/admin/clock': {
      id: '/admin/clock'
      path: '/clock'
      fullPath: '/admin/clock'
      preLoaderRoute: typeof AdminClockImport
      parentRoute: typeof AdminImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugImport
      parentRoute: typeof ProblemsImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexImport
      parentRoute: typeof ProblemsImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminClockRoute: typeof AdminClockRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClockRoute: AdminClockRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProblemsRouteChildren {
  ProblemsSlugRoute: typeof ProblemsSlugRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsSlugRoute: ProblemsSlugRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/admin/clock': typeof AdminClockRoute
  '/admin/users': typeof AdminUsersRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/clock': typeof AdminClockRoute
  '/admin/users': typeof AdminUsersRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/problems': typeof ProblemsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/admin/clock': typeof AdminClockRoute
  '/admin/users': typeof AdminUsersRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/problems'
    | '/admin/clock'
    | '/admin/users'
    | '/problems/$slug'
    | '/admin/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/admin/clock'
    | '/admin/users'
    | '/problems/$slug'
    | '/admin'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/problems'
    | '/admin/clock'
    | '/admin/users'
    | '/problems/$slug'
    | '/admin/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/leaderboard",
        "/problems"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/clock",
        "/admin/users",
        "/admin/"
      ]
    },
    "/leaderboard": {
      "filePath": "leaderboard.tsx"
    },
    "/problems": {
      "filePath": "problems.tsx",
      "children": [
        "/problems/$slug",
        "/problems/"
      ]
    },
    "/admin/clock": {
      "filePath": "admin/clock.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/problems/$slug": {
      "filePath": "problems/$slug.tsx",
      "parent": "/problems"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/problems/": {
      "filePath": "problems/index.tsx",
      "parent": "/problems"
    }
  }
}
ROUTE_MANIFEST_END */
