mutation CreateUser(
	$username: String!
	$password: String!
	$teamId: ID
	$role: UserRole!
	$name: String!
) {
	createUser(
		username: $username
		teamId: $teamId
		role: $role
		password: $password
		name: $name
	) {
		name
		id
		username
		teamId
		role
	}
}
