mutation CreateUser(
	$username: String!
	$password: String!
	$teamId: Int
	$role: UserRole!
) {
	createUser(
		username: $username
		teamId: $teamId
		role: $role
		password: $password
	) {
		id
		username
		teamId
		role
	}
}
