mutation SubmitProblem($code: String!, $slug: ID!, $output: String!) {
	judge(code: $code, slug: $slug, output: $output) {
		__typename
		... on JudgeErrorOutput {
			message
			errors
		}
		... on JudgeSuccessOutput {
			message
		}
	}
}
