mutation JudgeProblemMutation(
	$slug: String!
	$code: String!
	$output: String!
) {
	judge(slug: $slug, code: $code, output: $output) {
		__typename

		... on JudgeSuccessOutput {
			message
		}

		... on JudgeErrorOutput {
			message
			errors
		}
	}
}
