name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    name: "Build and Publish Image"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Container Metadata
        id: container_metadata
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/progsoc/fuzzjudge
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (Backend)
        uses: docker/build-push-action@v5
        id: docker_build_backend
        with:
          tags: ${{ steps.container_metadata.outputs.tags }}
          push: true
          labels: ${{ steps.container_metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/progsoc/fuzzjudge:latest