on:
  workflow_dispatch:

name: Publish Server
jobs:
  test-server:
    name: Test Bun
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # run any `bun` or `bunx` command
      - run: bun install
      - run: cd server && bun test
  publish-server:
    name: Publish Bun
    needs: test-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          scope: '@progsoc'
          token: ${{ secrets.NPM_TOKEN }}
      # run any `bun` or `bunx` command
      - run: bun install
      - name: Build JS
        run: bun run --filter @progsoc/fuzzjudge-server build
      - run: cd server && bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
      