on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test Bun
jobs:
  test:
    name: Test Bun
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test