on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Test Code
jobs:
  test-server:
    name: Test Bun
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # run any `bun` or `bunx` command
      - run: bun install
      - run: cd server && bun test
  test-svelte:
    name: Test Svelte
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Install Deps
        run: bun install
      - name: Build Types
        run: bun run --filter @progsoc/fuzzjudge-server build
      - name: Build Types
        run: bun run tsc -b --verbose
      - name: Check Svelte Types
        run: bun run --filter @progsoc/fj-svelte check
      